import Providers from '@/components/Providers';
import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import './globals.css';
import { cn } from '@/lib/utils';
import Navbar from '@/components/Navbar';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
	title: 'Mindrush',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					// 3. Use the variables directly from the correct imports
					GeistSans.variable,
					GeistMono.variable,
					'antialiased min-h-screen pt-16',
				)}
			>
				<Providers>
					<Navbar />
					{children}
					<Toaster richColors />
				</Providers>
			</body>
		</html>
	);
}
